# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the source branch
on:
  push:
    branches: [ source ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: debian:trixie

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install pre-reqs
        run: |
          apt-get update && apt-get install -y --no-install-recommends git ca-certificates

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Cache deps
        uses: actions/cache@v6
        env:
          cache-name: cache-ikiwiki-deps
        with:
          path: |
            ~/perl5
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Install ikiwiki
        run: |
          apt-get install -y --no-install-recommends \
            ikiwiki \
            libtext-multimarkdown-perl \
            libimage-magick-perl \
            librsvg2-bin \
            cpanminus \
            build-essential \
            libhighlight-perl \
            latexml \
            tex4ht \
            biber \
            texlive-bibtex-extra \
            texlive-latex-base \
            texlive-latex-extra \
            texlive-latex-recommended \
            texlive-pictures \
            graphviz \

          cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
          cpanm -n YAML::Any YAML::XS Sort::Naturally LaTeXML

      - name: Run ikiwiki
        run: |
          git config --global --add safe.directory $PWD

          eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
          export PERL5LIB="$PERL5LIB:./.ikiwiki-plugins/p5-IkiWiki-Plugin-github/lib"

          ikiwiki --setup NacrePerl.setup

      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: '../_site'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5

      - name: Push checkout back
        run: |
          cd $GITHUB_WORKSPACE
          git push
